---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-04e59c05167ea7bd5"
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: Provision M5 developer instance
      ec2:
        key_name: m1 key
        group: 
          - m5-ig-developer
          - m5-ig-postgres-tag
        instance_type: t3.nano
        image: "{{ ami_id }}"
        instance_tags:
          Name: M5_developer_instance
        wait: yes
        vpc_subnet_id: "{{ public_subnet1.subnet.id  }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Name: M5_developer_instance
      register: ec2
