---
- hosts: localhost
  gather_facts: no
  vars:
    pg_secret: {
      "username": "image_gallery",
      "password": "simple",
      "engine": "postgres",
      "host": "{{ rds.instance.endpoint }}",
      "port": 5432,
      "dbInstanceIdentifier": "m5-image-gallery",
      "database_name": "image_gallery"
      }
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: Add database secret to secrets manager
      aws_secret:
        name: 'sec-m5-image-gallery'
        state: present
        secret_type: 'string'
        secret: '{{ pg_secret | to_json }}'
    
