---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-04e59c05167ea7bd5"
  module_defaults:
    group/aws: 
      region: "us-west-1"
  tasks: 
    - name: Provision Adkins Test Instance
      ec2: 
        key_name: m1 key
        group: Module5-developer-sg
        instance_type: t3.nano
        image: "{{ ami_id }}"
        instance_tags: 
          Name: Module_5 Adkins ansible
          Module: 5
          Department: Accounting
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id  }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag: 
          Name: Module 5 Adkins ansible
    - name: Provision Marys Test Instance
      ec2:
        key_name: m1 key
        group: Module5-developer-sg
        instance_type: t3.nano
        image: "{{ ami_id }}"
        instance_tags:
          Name: Module_5 Mary ansible
          Module: 5
          Department: Accounting
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id  }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Name: Module 5 Mary ansible
    - name: Provision Sallys Test Instance
      ec2:
        key_name: m1 key
        group: Module5-developer-sg
        instance_type: t3.nano
        image: "{{ ami_id }}"
        instance_tags:
          Name: Module_5 Sally ansible
          Module: 5
          Department: DevOps
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id  }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Name: Module 5 Sally ansible
