---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - rds_subnet_group:
        name: m5-ig-private-dbroup
        subnets:
          - "{{ private_subnet1.subnet.id }}"
          - "{{ private_subnet2.subnet.id }}"
        state: present
        description: Subnet for m5 project
      register: rds_subnet
    - local_action:
        module: rds
        command: restore
        snapshot: image-gallery-ss-1
        instance_name: m5-image-gallery
        subnet: "{{ rds_subnet.subnet_group.name }}"
        wait: yes
        wait_timeout: 600
        tags:
          Name: m5-image-gallery
      register: rds
    - local_action:
        module: rds
        command: modify
        instance_name: m5-image-gallery
        vpc_security_groups: "{{ ig_postgres.group_id }}"
    - name: debug rds
      debug: var=rds
